version: '3.8'

services:
  btc-address-matcher:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: btc_address_matcher
    deploy:
      resources:
        limits:
          cpus: '10.0'
    volumes:
      - ./logs:/app/logs
      - ./results:/app/results
      - ./data.txt:/app/data.txt
    command: python docker_mode.py