version: '3.8'

services:
  btc-address-matcher:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: btc_address_matcher
    deploy:
      resources:
        limits:
          cpus: '15.0'
    volumes:
      - ./logs:/app/logs
      - ./results:/app/results
      - ./data.txt:/app/data.txt
    command: python local_mode_range_2.py --start= --end=000000000000000000000000000000000000000000000007ffffffffffffffff --num_processes=15